//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agreements
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public int TypeID { get; set; }
        public int StatusID { get; set; }
        public string Number { get; set; }
        public System.DateTime DataOpen { get; set; }
        public Nullable<System.DateTime> DataClose { get; set; }
        public string Note { get; set; }
    
        public virtual Persons Persons { get; set; }
        public virtual StatusAgreements StatusAgreements { get; set; }
        public virtual Types Types { get; set; }
    }
}
