//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgLicenses
    {
        public OrgLicenses()
        {
            this.Persons = new HashSet<Persons>();
        }
    
        public int ID { get; set; }
        public string LicenseNumber { get; set; }
    
        public virtual ICollection<Persons> Persons { get; set; }
    }
}
