//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persons
    {
        public Persons()
        {
            this.Agreements = new HashSet<Agreements>();
        }
    
        public int ID { get; set; }
        public Nullable<int> OrgLicenseID { get; set; }
        public int VerietyID { get; set; }
        public int StatusID { get; set; }
        public string Inn { get; set; }
        public string Type { get; set; }
        public string Shifer { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual ICollection<Agreements> Agreements { get; set; }
        public virtual OrgLicenses OrgLicenses { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Verieties Verieties { get; set; }
    }
}
