//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WPFEntities1 : DbContext
    {
        public WPFEntities1()
            : base("name=WPFEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Agreements> Agreements { get; set; }
        public DbSet<OrgLicenses> OrgLicenses { get; set; }
        public DbSet<Persons> Persons { get; set; }
        public DbSet<StatusAgreements> StatusAgreements { get; set; }
        public DbSet<Statuses> Statuses { get; set; }
        public DbSet<Types> Types { get; set; }
        public DbSet<Verieties> Verieties { get; set; }
    }
}
